### ISSUE TITLE
Registration Supplement in django 1.7.5

### ISSUE THREAD

**Issue by jflow** [lambdalisue/django-inspectional-registration#32]
When following your instructions on supplemental information on registration I get the following errors.

Django = 1.7.5
Python = 3.4.2

core.MyRegistrationSupplement.registration_profile: (fields.E304) Reverse accessor for 'MyRegistrationSupplement.registration_profile' clashes with reverse accessor for 'DefaultRegistrationSupplement.registration_profile'.
	HINT: Add or change a related_name argument to the definition for 'MyRegistrationSupplement.registration_profile' or 'DefaultRegistrationSupplement.registration_profile'.
core.MyRegistrationSupplement.registration_profile: (fields.E305) Reverse query name for 'MyRegistrationSupplement.registration_profile' clashes with reverse query name for 'DefaultRegistrationSupplement.registration_profile'.
	HINT: Add or change a related_name argument to the definition for 'MyRegistrationSupplement.registration_profile' or 'DefaultRegistrationSupplement.registration_profile'.
registration.DefaultRegistrationSupplement.registration_profile: (fields.E304) Reverse accessor for 'DefaultRegistrationSupplement.registration_profile' clashes with reverse accessor for 'MyRegistrationSupplement.registration_profile'.
	HINT: Add or change a related_name argument to the definition for 'DefaultRegistrationSupplement.registration_profile' or 'MyRegistrationSupplement.registration_profile'.
registration.DefaultRegistrationSupplement.registration_profile: (fields.E305) Reverse query name for 'DefaultRegistrationSupplement.registration_profile' clashes with reverse query name for 'MyRegistrationSupplement.registration_profile'.
	HINT: Add or change a related_name argument to the definition for 'DefaultRegistrationSupplement.registration_profile' or 'MyRegistrationSupplement.registration_profile'.

Your quick tutorial is very sparse and does not mention the files you have to add manually to your setup to get things working. Nor how to integrate your forms into a sites design, I am new to django, so I understand I may be missing things. But you should help the new guys out! 

So is this a incompatible version? More documentation is always desired.

**Comment by lambdalisue** [comment]
> HINT: Add or change a related_name argument to the definition for 

https://www.google.co.jp/search?q=HINT%3A+Add+or+change+a+related_name+argument+to+the+definition+for&oq=HINT%3A+Add+or+change+a+related_name+argument+to+the+definition+for&aqs=chrome..69i57j69i58.733j0j7&sourceid=chrome&es_sm=91&ie=UTF-8

It is a quite common situation in Django

**Comment by jflow** [comment]
A google link is nice to have, but still doesn't address the issue!  If this is so common of a thing why not put it into YOUR documentation stating, THIS MUST BE DONE AS WELL. 

Having read the other issues. You seem to have a serious lack of will in fixing your documentation.

**Comment by lambdalisue** [comment]
Well I thought that you have a extra `ForeginKey` to a registration supplement in your model (imagine from your error output). If it's not, let me know more detail about your code (definition of the class or whatever). I'm welcome to help you to solve the problem.

> why not put it into YOUR documentation stating, THIS MUST BE DONE AS WELL.

It is too common. I even didn't think that people would stack with this.

> Having read the other issues. You seem to have a serious lack of will in fixing your documentation. Specially when what the problems is because of your base model.

I'm sorry for that the documentation is full enough but writing documentation is also tough work.

**Comment by yorickchan** [comment]
Please refer to the accepted answer of the following:

http://stackoverflow.com/questions/5611410/related-name-argument-not-working-as-expected-in-django-model

> If you have `ForeignKey` relationships in an abstract base class every class inheriting from it will have this relationship. As a result of this you must not 'hardcode' its `related_name`, because all sub classes will try to create the same accessor on the related class

In this case, the error is due to the `related_name='_supplement'` in `RegistrationSupplementBase`, not by any extra `ForeignKey` in the subclassed supplement.

**Comment by lambdalisue** [comment]
Wow! I didn't even notice that. Thanks for the clear direction. Now I got what the problem in the case.
https://docs.djangoproject.com/en/dev/topics/db/models/#be-careful-with-related-name

Well I **MUST** fix this problem, I'll lookup the code and will fix ASAP.

**Comment by lambdalisue** [comment]
It is a bit difficult to solve. I need time to consider the case deeply. Sorry for taking time.

**Comment by timkofu** [comment]
Is this still an issue in 1.7.7? Because this package is exactly what I need, but I don't want any nasty surprises in production.

**Comment by lambdalisue** [comment]
@timkofu 
Let me explain the situation a bit. It is not version of django related issue thus the issue remains in 1.7.7 as well.

While django-inspectional-registration define `related_name='_supplement'` in `RegistrationSupplementBase` which is an abstract class of registration supplement, if you have **more than two subclass** of the `RegistrationSupplementBase`, django  cannot figure out which class is connected to `_supplement` field thus complain about that. Thus **if you have only a single subclass of the `RegistrationSupplementBase`**, the issue won't comes up (that's why I didn't notice this issue a long time). So to deal with this issue, follow the rules below:

1. Do not create more than a single subclass of `RegistrationSupplementBase`, indicating that do not import `registration.supplements.default.models` in any place which will add `DefaultRegistrationSupplement`
2. Do not use `related_name='_supplement'` in your code in case.

While the supplement information feature of django-inspectional-registration strongly rely on `_supplement` field, it would take a time to discover/fix the issue and currently I can't take enough time to even discover. I'm sorry for this inconvenience.
