### ISSUE TITLE
user completed the registration filling-in the password, but the browser's URL is /registration/activate/complete/

### ISSUE THREAD

**Issue by murdav** [lambdalisue/django-inspectional-registration#33]
Dear All,

The user gets the specific user accepted email;  he/she fills-in the passwords and automatically he/she is redirected to the wanted website page (@login_required).
The wanted page is loaded correctly, but the browser's URL is http://***/registration/activate/complete/ instead of the correct URL. 
Why?

Thanks,

D

**Comment by lambdalisue** [comment]
I'm sorry but I don't really get the situation. Could you explain the situation sequentially like

1. User "A" access a url "http://foo/registration/brabrabra"
2. User "A" fill....

**Comment by murdav** [comment]
Sorry lambdalisue!

1. User wants to access a login required page, hence Djando redirects to
http://localhost:8000/registration/register/?next=/login-required-page/
This page contains 2 forms: sign up and sign in.

2. It's a new user, hence he decided to compile the requested fields and submits it

3. Now the user has to wait until an administrator verifies the registration
User page is http://localhost:8000/registration/register/complete/

4. An adminstrator accepted the user registration through the Djando admin and an email has been sent to the user

5. User received the registration confirmation email and loads the page:
http://localhost:8000/registration/activate/925f04e3b8c8982a73887be13f7b17979c7ffe2e/
He provides password and check-password values.

6. The problem is in this point!
The page to be loaded when user submitted the passwords-selected-form should have been:
http://localhost:8000/login-required-page/, but it's http://localhost:8000/registration/activate/complete/. 
Browser's URL is http://localhost:8000/registration/activate/complete/.
But the page http://localhost:8000/registration/activate/complete/ is indeed http://localhost:8000/login-required-page/.

Thanks again,

D

**Comment by lambdalisue** [comment]
Hum. It seems that the behaviour is correct. You are probably misunderstood the following

> he page to be loaded when user submitted the passwords-selected-form should have been:
http://localhost:8000/login-required-page/

Actually, it should NOT. Registration and authentication is different thus django-inspectional-registration **always** redirect to `http://xxxxx/registration/activate/complete/` after the activation has completed. I use this page to show an initial instruction of the website for the login user.

If you want to change this behaviour, inherit `DefaultRegistrationBackend` and override `get_activation_complete_url` method. However, django-inspectional-registration **does not** keep which url the anonymous user accessed and denied . **Thus you will never be able to know "which url the anonymous user tried to access" in `get_activation_complete_url` method**.
This is a basic concept while inspection might take a while and nobody would want to access the url he/she tried to access weeks ago. Note that the url he/she tried to access might be not found after weeks :-) That's why I don't really care about which url he/she tried to access before in **registration steps**.

See: https://django-inspectional-registration.readthedocs.org/en/latest/registration.backends.default.html#registration.backends.default.DefaultRegistrationBackend.get_activation_complete_url

**Comment by murdav** [comment]
Many thanks for prompt reply!
That was the applied workflow for letting you understand. 
Basically when the users confirm their passwords they should be redirected to the same webpage (login_required) and not to http://xxxxx/registration/activate/complete/. 
But http://xxxxx/registration/activate/complete/ contains/is the "wanted-page", the difference is that the Browser's URL is http://xxxxx/registration/activate/complete/ instead of http://xxxxx/wanted-page

D

**Comment by lambdalisue** [comment]
> Basically when the users confirm their passwords they should be redirected to the same webpage (login_required) and not to http://xxxxx/registration/activate/complete/. 

Agree. And I think the current behaviour is what you want (See Case 2.)

> But http://xxxxx/registration/activate/complete/ contains/is the "wanted-page", the difference is that the Browser's URL is http://xxxxx/registration/activate/complete/ instead of http://xxxxx/wanted-page

I totally don't understand this point... So you meant that the contents of the page is `http://xxxxx/wanted-page` but the url is `http://xxxxx/registration/activate/complete/`? Then what happen if you directly access to `http://xxxxx/registration/activate/complete/`? Are you sure it is not because of the browser cache or so on? It is quite mysterious situation for me.... I have never face that kind of situation.

Hum... Probably I didn't get your point. Let me explain the **willing behaviour** of django-inspectional-registration. Are these behaviour what you want?

#### Case 1: User is already logged in

If the user is already logged into the website, the user can access the `http://xxxxx/login_required`.

#### Case 2: User has not logged in yet but have an account

If the user has not logged into the website yet, the access will automatically be redirected into `http://xxxxx/registration/login?next=/login_required`. If he provide his username and password and click "login", the access will automatically be redirected into `http://xxxxx/login_required` which the user tried to access.

#### Case 3: User does not have an account yet

If the user does not have an account yet, the access will automatically be redirected into `http://xxxxx/registration/login?next=/login_required` **but**.
While he does not have a correct account, he cannot provide his username and password thus he somehow (click link or whatever) access to `http://xxxxx/registration/register` and send a registration request.
After a week later (or whenever), an administrator of the website noticed that there is a registration request, thus the administrator accept the registration and an email is sent to the user.
He (the user) got an email from administrator with an activation link `http://xxxxx/registration/activate/<hash>/` so he clicked the link and asked to provide his new password for his new account.
Once he provide his new password, he is redirected to `http://xxxxx/registration/login` thus he provide his new username and password (if you use [`registration.contrib.autologin`](https://django-inspectional-registration.readthedocs.org/en/latest/registration.contrib.autologin.html#module-registration.contrib.autologin), the behavior is a bit different at this point).
Now he is logged into the website, thus he can access to `http://xxxxx/login_required` like Case 1.
If he logged out, follow Case 2.

**Comment by murdav** [comment]
> Case 1: User is already logged in

Exactly, the workflow is what you described.


> Case 2: User has not logged in yet but have an account

Exactly, the workflow is what you described.


> Case 3: User does not have an account yet
> If the user does not have an account yet, the access will automatically be redirected
> into http://xxxxx/registration/login?next=/login_required but.

Exactly


> While he does not have a correct account, he cannot provide his username and password 
> thus he somehow (click link or whatever) access to 
> http://xxxxx/registration/register and send a registration request.

This page contains 2 forms login and registration.
If user provides username and password he is redirected to http://xxxxx/login_required correctly, otherwise he has to insert 
the requested fields in the registration form and submit it.


> After a week later (or whenever), an administrator of the website noticed 
> that there is a registration request, thus the administrator 
> accept the registration and an email is sent to the user.

Exactly.


> He (the user) got an email from administrator with an activation 
> link http://xxxxx/registration/activate/<hash>/ so he clicked the link and asked 
> to provide his new password for his new account.

Exactly


> Once he provide his new password, he is redirected to 
> http://xxxxx/registration/login *

No, here I have the issue.
The user has provided the first password (+password check) after submitting it he is redirected to http://xxxxx/registration/activate/complete/, but this page is indeed http://xxxxx/login_required, 
but in the browser's URL we have http://xxxxx/registration/activate/complete/.
Following my wanted workflow when the users have provided the first password (+password check) they must be redirected to http://xxxxx/login_required. 

The strange behaviour should be caused by
###### return HttpResponse(login_required)  # lambdalisue this is the line? ######


This is profiles/views.py

	def auth_and_login(request):
	    """
	    """
	    registration_url = reverse('registration_register')
	
	    if request.method == 'POST':  # If the form has been submitted
	        login_required = reverse('login-required')
	
	        user = authenticate(username=request.POST.get('username'),
	                            password=request.POST.get('password'))
	        if user is not None:
	            if user.is_active:
	                login(request, user)
	                if request.POST.get('remember_me'):
	                    request.session.set_expiry(0)
	                return HttpResponse(login_required)  # lambdalisue this is the line?
	            else:
	                # Return a 'disabled account' error message
	                error = _('Your account has been disabled.')
	                return HttpResponseBadRequest(error)
	        else:
	            # Return an 'invalid login' error message.
	            error = _('Username and password didn\'t match. Please try again.')
	            return HttpResponseBadRequest(error)
	    else:
	        return HttpResponse(registration_url)

**Comment by lambdalisue** [comment]
Now I got. So **you use your own view instaed of a default view of django-inspectional-registration**. Then **it is not actually django-inspectional-registration issue but your code issue**.

I don't really get what kind of behaviour you want but use [`HttpResponseRedirect`](https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpResponseRedirect) instead of `HttpResponse` and everything would work I guess. 

Read a documentation of [`HttpResponse`](https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpResponse.__init__) carefully, **what you are doing is completely wrong at `HttpResponse` line** because you specify the url (`registration_url` or `login_required`) as a content of the webpage and that's why you will get `login_required` as a content of `http://xxxxx/registration/activate/complete`.

**Comment by murdav** [comment]
A huge thank lambdalisue for point me in the correct direction!

**Comment by murdav** [comment]
I got why it has been developed like that.
It's an AJAX form and the view.py+JS are described in this answer: http://stackoverflow.com/questions/13784136/django-ajax-login-form
